name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set YML
      run: |
          echo "${{ secrets.APPLICATION_PROD_YML }}" > src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_TEST_YML }}" > src/test/resources/application.yml

    - name: Build with Gradle Wrapper
      run: ./gradlew build
